### ISSUE TITLE
Scala-maxmind-iplookups runtime error (java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode)

### ISSUE THREAD

**Issue by minchenGrab** [snowplow/scala-maxmind-iplookups#115]
I am able to compile scala-maxmind-iplookups, but got the following runtime error, please help:

Exception in thread “main” java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)V
at com.maxmind.db.Decoder.decodeArray(Decoder.java:272)
at com.maxmind.db.Decoder.decodeByType(Decoder.java:156)
at com.maxmind.db.Decoder.decode(Decoder.java:147)
at com.maxmind.db.Decoder.decodeMap(Decoder.java:281)
at com.maxmind.db.Decoder.decodeByType(Decoder.java:154)
at com.maxmind.db.Decoder.decode(Decoder.java:147)
at com.maxmind.db.Decoder.decode(Decoder.java:87)
at com.maxmind.db.Reader.(Reader.java:132)
at com.maxmind.db.Reader.(Reader.java:116)
at com.maxmind.geoip2.DatabaseReader.(DatabaseReader.java:66)
at com.maxmind.geoip2.DatabaseReader.(DatabaseReader.java:54)
at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:160)
at com.snowplowanalytics.maxmind.iplookups.IpLookups$$anonfun$getService$1.apply(IpLookups.scala:137)
at com.snowplowanalytics.maxmind.iplookups.IpLookups$$anonfun$getService$1.apply(IpLookups.scala:132)
at scala.Option.map(Option.scala:146)
at com.snowplowanalytics.maxmind.iplookups.IpLookups.getService(IpLookups.scala:132)
at com.snowplowanalytics.maxmind.iplookups.IpLookups.(IpLookups.scala:117)
at com.snowplowanalytics.maxmind.iplookups.IpLookups$$anonfun$createFromFiles$2$$anonfun$apply$1.apply(IpLookups.scala:57)
at com.snowplowanalytics.maxmind.iplookups.IpLookups$$anonfun$createFromFiles$2$$anonfun$apply$1.apply(IpLookups.scala:57)

**Comment by BenFradet** [comment]
You've got conflicting jackson versions on your classpath, the maxmind database uses 2.9.5: https://mvnrepository.com/artifact/com.maxmind.geoip2/geoip2/2.12.0

**Comment by minchenGrab** [comment]
How do I fix this? I am using scala with sbt. 

What included this line in my build.sbt:
libraryDependencies ++= Seq(
  "com.snowplowanalytics" %% "scala-maxmind-iplookups" % "0.5.0",
)

**Comment by minchenGrab** [comment]
I managed to the following to my build.sbt:

libraryDependencies ++= Seq(
  *"com.fasterxml.jackson.core" % "jackson-databind" % "2.9.3",*
  "com.snowplowanalytics" %% "scala-maxmind-iplookups" % "0.5.0",
)
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.fasterxml.jackson.**" -> "shaded.com.fasterxml.jackson.@1").inAll
)
